Issue/110 비밀번호 변경, 유저정보수정 API 변경.
yachugak/TOPLA pull request #112
Opened 2020-12-03 12:25 UTC by romaakk

2020-12-03 12:32 UTC, fnai approved these changes
참! 잘했어요! 도장쾅!

2020-12-04 07:50 UTC, henry174 requested changes

2020-12-04 07:50 UTC, henry174 commented on topla-spring/src/main/java/com/yachugak/topla/request/UpdatePushAlarmStatusRequestFormat.java
> +	public boolean isPushAlarmStatus() {
user entity의 `setPushAlarmStatus(boolean)`과 표기법 불일치
is 또는 set 둘 중 하나로 통일하세용

2020-12-04 07:57 UTC, romaakk commented on topla-spring/src/main/java/com/yachugak/topla/request/UpdatePushAlarmStatusRequestFormat.java
> +	public boolean isPushAlarmStatus() {
이거이 자동생성인 것이에오

2020-12-04 14:58 UTC, henry174 commented on topla-spring/src/main/java/com/yachugak/topla/request/UpdatePushAlarmStatusRequestFormat.java
> +	public boolean isPushAlarmStatus() {
boolean이 아니라 Boolean이라서 객체로 봤나 보네

2020-12-04 14:59 UTC, henry174 approved these changes

2020-12-05 09:29 UTC, merged